#!/usr/bin/env bash
# =============================================================================
# sysctl-performance.sh — sing-box gateway TCP 性能优化
#
# 作用：
#   1. 设置 tcp_notsent_lowat 降低小包延迟（无副作用，通用生效）
#   2. 在默认出口网卡上附加 fq qdisc（条件生效，需内核支持）
#
# 设计原则：
#   - 所有操作都经过检测，不会造成断网
#   - 自动恢复：写入 sysctl.d + 启动脚本，重启后策略依然有效
#   - 幂等：重复执行安全，不会重复追加
#   - 跨平台：自动检测 OpenRC / systemd 并选择对应持久化方式
# =============================================================================
set -euo pipefail

SYSCTL_CONF="/etc/sysctl.d/98-sing-box-performance.conf"

# --- 确保以 root 运行 ---
if [ "$(id -u)" -ne 0 ]; then
  echo "请以 root 运行." >&2
  exit 1
fi

# 检测 init 系统
INIT_SYSTEM="unknown"
if command -v rc-update >/dev/null 2>&1; then
  INIT_SYSTEM="openrc"
elif command -v systemctl >/dev/null 2>&1; then
  INIT_SYSTEM="systemd"
fi

# --- 1. sysctl: tcp_notsent_lowat + BBR 基础参数 ---
echo "=== 1. TCP sysctl 优化 ==="
mkdir -p "$(dirname "$SYSCTL_CONF")"

# 如果文件不存在，先创建
if [ ! -f "$SYSCTL_CONF" ]; then
  cat > "$SYSCTL_CONF" << 'EOF'
# sing-box gateway 性能参数
# 注意: 轻量内核（Alpine/Docker 等）可能不支持 net.core.default_qdisc
net.ipv4.tcp_congestion_control = bbr
net.ipv4.tcp_rmem = 4096 131072 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.tcp_slow_start_after_idle = 0
EOF
fi

# 清理之前可能写入的不兼容 default_qdisc 行
if grep -qs '^net.core.default_qdisc' "$SYSCTL_CONF"; then
  sed -i '/^net.core.default_qdisc/d' "$SYSCTL_CONF"
  echo "  清理了不兼容的 default_qdisc 配置行（部分内核不支持，改用 tc qdisc 替代）"
fi

# 追加 tcp_notsent_lowat（幂等：已有则跳过）
if grep -qs '^net.ipv4.tcp_notsent_lowat' "$SYSCTL_CONF"; then
  echo "  tcp_notsent_lowat 已配置，跳过."
else
  echo "net.ipv4.tcp_notsent_lowat = 131072" >> "$SYSCTL_CONF"
  echo "  ✓ tcp_notsent_lowat=131072 已写入 $SYSCTL_CONF"
fi

# 应用 sysctl（忽略未知键的警告）
sysctl -p "$SYSCTL_CONF" 2>/dev/null || sysctl -e -p "$SYSCTL_CONF" 2>/dev/null || true
echo "  当前 tcp_notsent_lowat=$(sysctl -n net.ipv4.tcp_notsent_lowat 2>/dev/null || echo 'N/A')"

# 通知 systemd 刷新 sysctl（可选，sysctl -p 已直接生效，但 systemd-sysctl 确保下次启动一致）
if [ "$INIT_SYSTEM" = "systemd" ] && command -v systemctl >/dev/null 2>&1; then
  systemctl restart systemd-sysctl 2>/dev/null || true
fi

# --- 2. tc qdisc: fq (需要内核支持) ---
echo ""
echo "=== 2. tc qdisc (fq) ==="

# 检测默认出口接口
IFACE=$(ip -4 route show default 2>/dev/null | awk '/default/ { print $5; exit }')
if [ -z "$IFACE" ]; then
  echo "  ⚠ 未检测到 IPv4 默认路由，跳过 qdisc 配置."
  exit 0
fi
echo "  默认出口接口: $IFACE"

# 检测内核是否支持 fq
FQ_ACTIVE=false
if tc qdisc show dev "$IFACE" 2>/dev/null | grep -q 'fq'; then
  echo "  fq qdisc 已在 $IFACE 上生效，跳过."
  FQ_ACTIVE=true
elif tc qdisc replace dev "$IFACE" root fq 2>/dev/null; then
  echo "  ✓ fq qdisc 已附加到 $IFACE"
  FQ_ACTIVE=true
else
  echo "  ⚠ 内核不支持 fq qdisc，跳过 (BBR 使用软件 pacing)"
  echo "    如需启用，请确保内核编译了 CONFIG_NET_SCH_FQ"
fi

# 显示当前 qdisc 状态
if [ "$FQ_ACTIVE" = "true" ]; then
  tc qdisc show dev "$IFACE" 2>/dev/null | head -1
fi

# --- 3. 持久化: 按 init 系统写入启动脚本 ---
echo ""
echo "=== 3. 持久化 ==="
echo "  检测到 init 系统: $INIT_SYSTEM"

if [ "$FQ_ACTIVE" != "true" ]; then
  echo "  fq 未启用，跳过持久化."
  # 清理旧文件
  rm -f /etc/local.d/singbox-qdisc.start /etc/systemd/system/singbox-qdisc.service
  echo "=== 完成 ==="
  echo "tcp_notsent_lowat=131072 已生效."
  exit 0
fi

if [ "$INIT_SYSTEM" = "openrc" ]; then
  # --- OpenRC: /etc/local.d/*.start ---
  LOCAL_D_SCRIPT="/etc/local.d/singbox-qdisc.start"
  cat > "$LOCAL_D_SCRIPT" << SCRIPTEOF
#!/bin/sh
# Auto-generated by sysctl-performance.sh (sing-box gateway)
# 确保 $IFACE 上启用 fq qdisc（BBR 需要正确 pacing）
[ -x /sbin/tc ] || [ -x /usr/sbin/tc ] || exit 0
/sbin/tc qdisc replace dev $IFACE root fq 2>/dev/null || /usr/sbin/tc qdisc replace dev $IFACE root fq 2>/dev/null || true
SCRIPTEOF
  chmod +x "$LOCAL_D_SCRIPT"
  echo "  ✓ 启动脚本已写入 $LOCAL_D_SCRIPT"
  rc-update add local boot 2>/dev/null || rc-update add local default 2>/dev/null || true
  echo "  ✓ local 服务已加入启动级别"

elif [ "$INIT_SYSTEM" = "systemd" ]; then
  # --- systemd: /etc/systemd/system/singbox-qdisc.service ---
  UNIT_FILE="/etc/systemd/system/singbox-qdisc.service"
  cat > "$UNIT_FILE" << UNITEOF
[Unit]
Description=sing-box gateway: attach fq qdisc for BBR pacing
After=network.target
Before=sing-box.service sing-box-tproxy.service

[Service]
Type=oneshot
ExecStart=/sbin/tc qdisc replace dev $IFACE root fq
RemainAfterExit=yes
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
UNITEOF
  echo "  ✓ systemd unit 已写入 $UNIT_FILE"
  systemctl daemon-reload 2>/dev/null || true
  systemctl enable singbox-qdisc.service 2>/dev/null || true
  echo "  ✓ singbox-qdisc.service 已启用"

else
  echo "  ⚠ 未知 init 系统 ($INIT_SYSTEM)，无法自动持久化 qdisc."
  echo "    请手动将以下命令加入开机启动："
  echo "    tc qdisc replace dev $IFACE root fq"
fi

echo ""
echo "=== 完成 ==="
echo "tcp_notsent_lowat=131072 + fq on $IFACE — 重启后依然生效."
